name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - run : docker image build --tag=ubuntu-cowsay:latest ./
      - run : docker container run --rm ubuntu-cowsay:latest bash -c "cat /README.md | /usr/games/cowsay"